language: go

go:
  - 1.8.x
  - master

rvm:
  - 2.4.0

matrix:
  allow_failures:
    - go: master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential rpm
  - sudo gem install fpm

script:
  - go get -t ./...
  - make
