.TH GWATCH 1
.SH NAME
gwatch \- execute a program periodically, graphing the output fullscreen
.SH SYNOPSIS
.B gwatch
[\fB\-\-behtvx\fR ]
[\fB\-n\fR \fISECONDS\fR]
.IR [command] ...
.SH DESCRIPTION
.B gwatch
.RS
Attempts to mimic the cli behavior of procps-ng
.B watch
but the output is graphed (technically plotted) instead of printed.
.B gwatch
will graph the first number it is able to find and discard every thing else.
.RE
.SH OPTIONS
.TP
.B //TODO Have options here.
Not finalized yet and I really don't want to edit this file too many times.
